language: python

python: 3.7

branches: develop

install:
  - pip install -U mkdocs-material

script:
  - mkdocs gh-deploy 

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 target-branch: master
